name: test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  yarn-install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js with GitHub Packages
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@uplift-ltd"
      - name: Cache node_modules
        uses: actions/cache@master
        id: cache-node
        env:
          cache-name: cache-node
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        # Always run this, so it throws if the package and lockfile don't match
        run: yarn install --non-interactive --frozen-lockfile --prefer-offline
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  yarn-build:
    runs-on: ubuntu-latest
    needs:
      - yarn-install
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js with GitHub Packages
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@uplift-ltd"
      - name: Restore dependencies
        uses: actions/cache@master
        env:
          cache-name: cache-node
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn build

  yarn-test:
    runs-on: ubuntu-latest
    needs: yarn-install
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js with GitHub Packages
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@uplift-ltd"
      - name: Restore dependencies
        uses: actions/cache@master
        env:
          cache-name: cache-node
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn test
